import {
  siAngular,
  siAnsible,
  siAppwrite,
  siAstro,
  siAirtable,
  siBitbucket,
  siBlender,
  siBootstrap,
  siBun,
  siCircleci,
  siCloudflare,
  siContentful,
  siCss,
  siCypress,
  siDart,
  siDiscord,
  siDjango,
  siDocker,
  siDotnet,
  siDrizzle,
  siElasticsearch,
  siEslint,
  siExpo,
  siExpress,
  siFastapi,
  siFigma,
  siFirebase,
  siFlask,
  siFlutter,
  siFramer,
  siGit,
  siGithub,
  siGithubactions,
  siGitlab,
  siGo,
  siGooglecloud,
  siGraphql,
  siHtml5,
  siHubspot,
  siInsomnia,
  siJavascript,
  siJest,
  siJira,
  siKotlin,
  siKubernetes,
  siLaravel,
  siLess,
  siLinear,
  siMailchimp,
  siMariadb,
  siMeilisearch,
  siMiro,
  siMongodb,
  siMysql,
  siNestjs,
  siNetlify,
  siNextdotjs,
  siNotion,
  siNpm,
  siNuxt,
  siPhp,
  siPhpstorm,
  siPnpm,
  siPocketbase,
  siPostgresql,
  siPostman,
  siPrettier,
  siPrisma,
  siPython,
  siRailway,
  siReact,
  siRedis,
  siRedux,
  siRender,
  siRust,
  siSanity,
  siSass,
  siShopify,
  siSketch,
  siSpring,
  siSqlite,
  siStorybook,
  siStrapi,
  siStripe,
  siSupabase,
  siSvelte,
  siSwift,
  siTailwindcss,
  siTerraform,
  siTrello,
  siTypescript,
  siUnity,
  siVercel,
  siVite,
  siVitest,
  siWebflow,
  siWebpack,
  siWebstorm,
  siWix,
  siWoocommerce,
  siWordpress,
  siYarn,
  siZapier,
  type SimpleIcon,
} from "simple-icons";

type Tool = {
  name: string;
  icon?: SimpleIcon;
};

export const toolCatalog: Tool[] = [
  { name: "HTML", icon: siHtml5 },
  { name: "CSS", icon: siCss },
  { name: "JavaScript", icon: siJavascript },
  { name: "TypeScript", icon: siTypescript },
  { name: "C#", icon: siDotnet },
  { name: "PHP", icon: siPhp },
  { name: "Python", icon: siPython },
  { name: "Go", icon: siGo },
  { name: "Rust", icon: siRust },
  { name: "Dart", icon: siDart },
  { name: "Kotlin", icon: siKotlin },
  { name: "Swift", icon: siSwift },
  { name: "MySQL", icon: siMysql },
  { name: "MariaDB", icon: siMariadb },
  { name: "PostgreSQL", icon: siPostgresql },
  { name: "SQLite", icon: siSqlite },
  { name: "MongoDB", icon: siMongodb },
  { name: "Redis", icon: siRedis },
  { name: "Elasticsearch", icon: siElasticsearch },
  { name: "React", icon: siReact },
  { name: "Next.js", icon: siNextdotjs },
  { name: "Vue.js" },
  { name: "Angular", icon: siAngular },
  { name: "Svelte", icon: siSvelte },
  { name: "Astro", icon: siAstro },
  { name: "Nuxt", icon: siNuxt },
  { name: "Node.js" },
  { name: "Express", icon: siExpress },
  { name: "NestJS", icon: siNestjs },
  { name: "Laravel", icon: siLaravel },
  { name: "Django", icon: siDjango },
  { name: "Flask", icon: siFlask },
  { name: "FastAPI", icon: siFastapi },
  { name: "Spring", icon: siSpring },
  { name: ".NET", icon: siDotnet },
  { name: "Flutter", icon: siFlutter },
  { name: "Unity", icon: siUnity },
  { name: "Blender", icon: siBlender },
  { name: "Figma", icon: siFigma },
  { name: "Sketch", icon: siSketch },
  { name: "Canva" },
  { name: "Miro", icon: siMiro },
  { name: "Git", icon: siGit },
  { name: "GitHub", icon: siGithub },
  { name: "GitLab", icon: siGitlab },
  { name: "Bitbucket", icon: siBitbucket },
  { name: "GitHub Actions", icon: siGithubactions },
  { name: "Docker", icon: siDocker },
  { name: "Kubernetes", icon: siKubernetes },
  { name: "Terraform", icon: siTerraform },
  { name: "Ansible", icon: siAnsible },
  { name: "Tailwind CSS", icon: siTailwindcss },
  { name: "Bootstrap", icon: siBootstrap },
  { name: "Sass", icon: siSass },
  { name: "Less", icon: siLess },
  { name: "GraphQL", icon: siGraphql },
  { name: "Redux", icon: siRedux },
  { name: "Webpack", icon: siWebpack },
  { name: "Vite", icon: siVite },
  { name: "npm", icon: siNpm },
  { name: "pnpm", icon: siPnpm },
  { name: "Yarn", icon: siYarn },
  { name: "Bun", icon: siBun },
  { name: "ESLint", icon: siEslint },
  { name: "Prettier", icon: siPrettier },
  { name: "Jest", icon: siJest },
  { name: "Vitest", icon: siVitest },
  { name: "Cypress", icon: siCypress },
  { name: "Playwright" },
  { name: "Storybook", icon: siStorybook },
  { name: "Postman", icon: siPostman },
  { name: "Insomnia", icon: siInsomnia },
  { name: "Prisma", icon: siPrisma },
  { name: "Drizzle", icon: siDrizzle },
  { name: "Supabase", icon: siSupabase },
  { name: "Firebase", icon: siFirebase },
  { name: "Appwrite", icon: siAppwrite },
  { name: "PocketBase", icon: siPocketbase },
  { name: "Cloudflare", icon: siCloudflare },
  { name: "Google Cloud", icon: siGooglecloud },
  { name: "Vercel", icon: siVercel },
  { name: "Netlify", icon: siNetlify },
  { name: "Railway", icon: siRailway },
  { name: "Render", icon: siRender },
  { name: "CircleCI", icon: siCircleci },
  { name: "Expo", icon: siExpo },
  { name: "Shopify", icon: siShopify },
  { name: "WooCommerce", icon: siWoocommerce },
  { name: "WordPress", icon: siWordpress },
  { name: "Webflow", icon: siWebflow },
  { name: "Framer", icon: siFramer },
  { name: "Wix", icon: siWix },
  { name: "Klaviyo" },
  { name: "Replo" },
  { name: "Mailchimp", icon: siMailchimp },
  { name: "HubSpot", icon: siHubspot },
  { name: "Contentful", icon: siContentful },
  { name: "Sanity", icon: siSanity },
  { name: "Strapi", icon: siStrapi },
  { name: "Notion", icon: siNotion },
  { name: "Jira", icon: siJira },
  { name: "Linear", icon: siLinear },
  { name: "Trello", icon: siTrello },
  { name: "Airtable", icon: siAirtable },
  { name: "Slack" },
  { name: "Discord", icon: siDiscord },
  { name: "Stripe", icon: siStripe },
  { name: "Zapier", icon: siZapier },
  { name: "Meilisearch", icon: siMeilisearch },
  { name: "PHPStorm", icon: siPhpstorm },
  { name: "WebStorm", icon: siWebstorm },
];

const toolByName = new Map(toolCatalog.map((tool) => [tool.name.toLowerCase(), tool]));

export function getTool(name: string) {
  return toolByName.get(name.toLowerCase());
}

export function ToolLogo({ name, className = "" }: { name: string; className?: string }) {
  const icon = getTool(name)?.icon;
  const fallback = name.trim().slice(0, 2).toUpperCase();

  return (
    <span className={`tool-logo ${className}`} aria-hidden="true">
      {icon ? (
        <svg viewBox="0 0 24 24" focusable="false" style={{ fill: `#${icon.hex}` }}>
          <path d={icon.path} />
        </svg>
      ) : (
        <span>{fallback}</span>
      )}
    </span>
  );
}
